export const optionsList = [
    { value: "Reservation", label: "Reservation" },
    { value: "Takeout", label: "Takeout" },
    { value: "Wifi", label: "Wifi" },
    { value: "Credit Card", label: "Credit Card" },
    { value: "Outdoor", label: "Outdoor" },
    { value: "Parking", label: "Parking" },
    { value: "Delivery", label: "Delivery" },
    { value: "Whellchair", label: "Whellchair" },
    { value: "Alcohol", label: "Alcohol" },
    { value: "Bar atmosphere", label: "Bar atmosphere" },
];

export const moodesList = [
    { value: "Romantic", label: "Romantic" },
    { value: "Party", label: "Party" },
    { value: "Busines", label: "Busines" },
    { value: "Groups", label: "Groups" },
    { value: "Children", label: "Children" },
    { value: "Local", label: "Local" },
];

export const foodTypesList = [
    { value: "Armenian", label: "Armenian" },
    { value: "African", label: "African" },
    { value: "American", label: "American" },
    { value: "Argentinean", label: "Argentinean" },
    { value: "Asian", label: "Asian" },
    { value: "Balti", label: "Balti" },
    { value: "Bar", label: "Bar" },
    { value: "Barbecue", label: "Barbecue" },
    { value: "Basque", label: "Basque" },
    { value: "Beer restaurants", label: "Beer restaurants" },
    { value: "Belgian", label: "Belgian" },
    { value: "Brazilian", label: "Brazilian" },
    { value: "Brew Pub", label: "Brew Pub" },
    { value: "British", label: "British" },
    { value: "Cafe", label: "Cafe" },
    { value: "Campania", label: "Campania" },
    { value: "China", label: "China" },
    { value: "Campania", label: "Campania" },
    { value: "Cantonese", label: "Cantonese" },
    { value: "Caribbean", label: "Caribbean" },
    { value: "Catalan", label: "Catalan" },
    { value: "Caucasian", label: "Caucasian" },
    { value: "Central American", label: "Central American" },
    { value: "Central Asian", label: "Central Asian" },
    { value: "Central European", label: "Central European" },
    { value: "Central-Italian", label: "Central-Italian" },
    { value: "Chinese", label: "Chinese" },
    { value: "Colombian", label: "Colombian" },
    { value: "Contemporary", label: "Contemporary" },
    { value: "Cuban", label: "Cuban" },
    { value: "Deli", label: "Deli" },
    { value: "Diner", label: "Diner" },
    { value: "Dining bars", label: "Dining bars" },
    { value: "Dutch", label: "Dutch" },
    { value: "European", label: "European" },
    { value: "Fast Food", label: "Fast Food" },
    { value: "French", label: "French" },
    { value: "Fusion", label: "Fusion" },
    { value: "Gastropub", label: "Gastropub" },
    { value: "German", label: "German" },
    { value: "Greek", label: "Greek" },
    { value: "Grill", label: "Grill" },
    { value: "Hawaiian", label: "Hawaiian" },
    { value: "Healthy", label: "Healthy" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Indian", label: "Indian" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "International", label: "International" },
    { value: "Irish", label: "Irish" },
    { value: "Italian", label: "Italian" },
    { value: "Japanese", label: "Japanese" },
    { value: "Korean", label: "Korean" },
    { value: "Latin", label: "Latin" },
    { value: "Lazio", label: "Lazio" },
    { value: "Medicinal foods", label: "Medicinal foods" },
    { value: "Mediterranean", label: "Mediterranean" },
    { value: "Mexican", label: "Mexican" },
    { value: "Middle Eastern", label: "Middle Eastern" },
    { value: "Moroccan", label: "Moroccan" },
    { value: "Neapolitan", label: "Neapolitan" },
    { value: "Nepali", label: "Nepali" },
    { value: "Peruvian", label: "Peruvian" },
    { value: "Pizza", label: "Pizza" },
    { value: "Pub", label: "Pub" },
    { value: "Romana", label: "Romana" },
    { value: "Romanian", label: "Romanian" },
    { value: "Russian", label: "Russian" },
    { value: "Sardinian", label: "Sardinian" },
    { value: "Seafood", label: "Seafood" },
    { value: "Shanghai", label: "Shanghai" },
    { value: "Sicilian", label: "Sicilian" },
    { value: "Soups", label: "Soups" },
    { value: "South American", label: "South American" },
    { value: "Southern-Italian", label: "Southern-Italian" },
    { value: "Spanish", label: "Spanish" },
    { value: "Steakhouse", label: "Steakhouse" },
    { value: "Street Food", label: "Street Food" },
    { value: "Sushi", label: "Sushi" },
    { value: "Swiss", label: "Swiss" },
    { value: "Thai", label: "Thai" },
    { value: "Turkish", label: "Turkish" },
    { value: "Tuscan", label: "Tuscan" },
    { value: "Venezuelan", label: "Venezuelan" },
    { value: "Vietnamese", label: "Vietnamese" },
    { value: "Wine Bar", label: "Wine Bar" },      
];